name: build-test-publish
run-name: ${{ github.actor }} is building, testing and publishing ğŸš€

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-and-test-native:
    name: ğŸ—ï¸ build Rust native ğŸ¦€
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Cache target dir
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: target/
          key: target-${{  github.run_number }}-${{ github.run_attempt }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: ğŸ—ï¸ build release
        run: cargo build --release
      - name: ğŸ” test release
        run: cargo test --release
  build-python:
    name: ğŸ—ï¸ build python ğŸ with maturin
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: maturin build
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release
  publish-createsio:
    name: ğŸ“¦ Publish to crates.io
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: build-and-test-native
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Restore cargo build
        uses: actions/cache/restore@v4
        with:
          path: target/
          key: target-${{  github.run_number }}-${{ github.run_attempt }}
      - run: ls
      - name: publish to crate.io
        run: cargo publish --no-verify --token ${{ secrets.CRATEIO_TOKEN }}

